let CONSTANTS = {

    ACTIVE_STATUS: 'ACTIVE',
    EXPIRES_STATUS: 'EXPIRED',
    INACTIVE_STATUS: 'INACTIVE',
    DELETED_STATUS: 'DELETED',
    FROZEN_STATUS: 'FROZEN',
    BLOCKED_STATUS: 'BLOCKED',

    DEBIT: 'debit',
    CREDIT: 'credit',
    WALLET: 'WALLET',

    NONE: 'NONE',
    STREAM_ADS: 'STREAM_ADS',
    VOD_ADS: 'VOD_ADS',

    OFFLINE: 'OFFLINE',
    ONLINE_STANDARD: 'ONLINE_STANDARD',
    ONLINE_PREMIUM: 'ONLINE_PREMIUM',

    STANDARD: 'STANDARD',
    FREE: 'FREE',
    VIP: 'VIP',
    PREMIUM: 'PREMIUM',

    ACCOUNT_TYPE: 'ACCOUNT_TYPE',
    PROMOTION: 'PROMOTION',

    RENT_TITLE:'RENT_TITLE',
    


}