//USER
module.exports.CREATE_USER_EVENT = 'CREATE_USER'
module.exports.UPDATE_USER_EVENT = 'UPDATE_USER'

//FAVORITES
module.exports.CREATE_USER_FAVORITE_EVENT = 'CREATE_USER_FAVORITE'
module.exports.UPDATE_USER_FAVORITE_EVENT = 'UPDATE_USER_FAVORITE'

//ACCOUN TYPES
module.exports.CREATE_ACCOUNT_TYPE_EVENT = 'CREATE_ACCOUNT_TYPE'
module.exports.UPDATE_ACCOUNT_TYPE_EVENT = 'UPDATE_ACCOUNT_TYPE'
module.exports.CREATE_ACCOUNT_CONFIG_EVENT = 'CREATE_ACCOUNT_CONFIG'
module.exports.DELETE_ACCOUNT_CONFIG_EVENT = 'DELETE_ACCOUNT_CONFIG'
module.exports.UPDATE_ACCOUNT_CONFIG_EVENT = 'UPDATE_ACCOUNT_CONFIG'


/// WALLET  
module.exports.CREATE_USER_WALLET_EVENT = 'CREATE_USER_WALLET'
module.exports.UPDATE_USER_WALLET_EVENT = 'UPDATE_USER_WALLET'

//VOD CONTINUE WATCH 
module.exports.UPDATE_USER_CONTINUE_WATCH_LIST = 'UPDATE_USER_CONTINUE_WATCH_LIST'
module.exports.CREATE_USER_CONTINUE_WATCH_LIST = 'CREATE_USER_CONTINUE_WATCH_LIST'

// WatchList
module.exports.CREATE_USER_WATCH_LIST = 'CREATE_USER_WATCHLIST'
module.exports.REMOVE_USER_WATCH_LIST = 'REMOVE_USER_WATCHLIST'
